### ISSUE TITLE
Empty parentRelations fallback returns full product collection 

### ISSUE THREAD

**Issue by rexterkate-adwise** [magmodules/magento2-channable#222]
Hi,

the `getParents` function in `Model/Collection/Products.php` has a fallback when the `parentRelations` are empty, it returns `$this->productCollection`.

This should return an empty collection (according the comment), but it returns the full product collection without filtering instead. 

We are running into performance problems because of of this with a webshop with a rather large amount of products

**Comment by Frank-Magmodules** [comment]
Hello @rexterkate-adwise, again, i appreciate you bringing this issue to our attention. 

I'm happy to inform you that we've released a [new version](https://github.com/magmodules/magento2-channable/releases/tag/1.18.2) of the plugin addressing the reported issue. Since I believe this update resolves your concern, I'm closing the issue for now. 

However, please don't hesitate to reopen or comment if you find further issues or have any additional feedback.
