### ISSUE TITLE
[BUG] Discount not included on invoice

### ISSUE THREAD

**Issue by Skullsneeze** [magmodules/magento2-channable#227]
## Description

When syncing an order with a discount the discount is applied to the order grand total, but is not reflected in the total paid on the invoice.

## Steps to reproduce

- Enable and configure order imports
- Ensure invoice creation is enabled
- Import an order with a discount.

## Expected result

- The order is imported
- The invoice is created
- The discount is applied on both the order and the invoice

## Actual result

- The order is imported
- The invoice is created
- The discount is applied on the order
- The discount is **not** applied on the invoice

## Related PR

I've opened PR #226 which resolved the issue for me on our test environment. It explicitly adds the discount information to the invoice during creation.

**Comment by Marvin-Magmodules** [comment]
Hello @Skullsneeze, we appreciate you bringing this issue to our attention and thank you for opening up an PR for this!

I'm happy to inform you that we've released a [new version](https://github.com/magmodules/magento2-channable/releases/tag/1.18.3) of the plugin addressing the reported issue and merged this PR. Since I believe this update resolves your concern, I'm closing the issue for now.
